export const dummyTickets = [
  {
    id: "TK-001",
    fullName: "Biodun Adewale",
    email: "naana_417@hotmail.com",
    phone: "08173456789",
    VIP: "3",
    regular: "0",
  },
  {
    id: "TK-002",
    fullName: "Naana Mensah",
    email: "naana.mensah@gmail.com",
    phone: "08034561234",
    VIP: "1",
    regular: "2",
  },
  {
    id: "TK-003",
    fullName: "Emeka Okafor",
    email: "emeka.okafor@yahoo.com",
    phone: "07099887766",
    VIP: "0",
    regular: "4",
  },
  {
    id: "TK-004",
    fullName: "Fatima Bello",
    email: "fatima.bello@gmail.com",
    phone: "08122334455",
    VIP: "2",
    regular: "1",
  },
  {
    id: "TK-005",
    fullName: "Daniel Ojo",
    email: "daniel.ojo@mail.com",
    phone: "09011223344",
    VIP: "5",
    regular: "0",
  },
  {
    id: "TK-006",
    fullName: "Grace Johnson",
    email: "grace.johnson@gmail.com",
    phone: "08155667788",
    VIP: "1",
    regular: "3",
  },
  {
    id: "TK-007",
    fullName: "Tolu Akin",
    email: "tolu.akin@yahoo.com",
    phone: "07044556677",
    VIP: "0",
    regular: "6",
  },
  {
    id: "TK-008",
    fullName: "Hassan Musa",
    email: "hassan.musa@gmail.com",
    phone: "08199887711",
    VIP: "4",
    regular: "1",
  },
  {
    id: "TK-009",
    fullName: "Chioma Eze",
    email: "chioma.eze@mail.com",
    phone: "09022334455",
    VIP: "2",
    regular: "2",
  },
  {
    id: "TK-010",
    fullName: "Samuel Ibrahim",
    email: "samuel.ibrahim@gmail.com",
    phone: "08166778899",
    VIP: "1",
    regular: "5",
  },
];

export const dummyEvents = [
  {
    event: "The Grand Pass Event",
    date: "5 July 2026",
    category: "Concert",
    ticket: 40,
    revenue: "₦30,000.00",
    status: "Upcoming",
  },
  {
    event: "Lagos Tech Summit",
    date: "12 July 2026",
    category: "Conference",
    ticket: 120,
    revenue: "₦150,000.00",
    status: "Upcoming",
  },
  {
    event: "Startup Connect 2026",
    date: "18 July 2026",
    category: "Networking",
    ticket: 85,
    revenue: "₦95,000.00",
    status: "Upcoming",
  },
  {
    event: "Afrobeats Live Experience",
    date: "25 July 2026",
    category: "Concert",
    ticket: 250,
    revenue: "₦450,000.00",
    status: "Upcoming",
  },
  {
    event: "Women in Business Forum",
    date: "2 August 2026",
    category: "Seminar",
    ticket: 65,
    revenue: "₦78,000.00",
    status: "Upcoming",
  },
  {
    event: "Creative Designers Meetup",
    date: "9 August 2026",
    category: "Workshop",
    ticket: 50,
    revenue: "₦42,500.00",
    status: "Ongoing",
  },
  {
    event: "Digital Marketing Masterclass",
    date: "15 August 2026",
    category: "Training",
    ticket: 90,
    revenue: "₦135,000.00",
    status: "Upcoming",
  },
  {
    event: "Real Estate Investors Forum",
    date: "22 August 2026",
    category: "Conference",
    ticket: 70,
    revenue: "₦110,000.00",
    status: "Completed",
  },
  {
    event: "Youth Empowerment Summit",
    date: "29 August 2026",
    category: "Summit",
    ticket: 180,
    revenue: "₦220,000.00",
    status: "Completed",
  },
  {
    event: "Fashion & Lifestyle Expo",
    date: "5 September 2026",
    category: "Exhibition",
    ticket: 140,
    revenue: "₦175,000.00",
    status: "Upcoming",
  },
];

export const tickets = [
  {
    id: "TK-001",
    fullName: "Biodun Adewale",
    email: "naana_417@hotmail.com",
    phoneNumber: "08173456789",
    regular: 2,
    vip: 5,
  },
  {
    id: "TK-002",
    fullName: "Grace Johnson",
    email: "grace.johnson@gmail.com",
    phoneNumber: "08034561234",
    regular: 4,
    vip: 1,
  },
  {
    id: "TK-003",
    fullName: "Daniel Ojo",
    email: "daniel.ojo@yahoo.com",
    phoneNumber: "07099887766",
    regular: 3,
    vip: 2,
  },
  {
    id: "TK-004",
    fullName: "Chioma Eze",
    email: "chioma.eze@mail.com",
    phoneNumber: "08122334455",
    regular: 1,
    vip: 4,
  },
  {
    id: "TK-005",
    fullName: "Hassan Musa",
    email: "hassan.musa@gmail.com",
    phoneNumber: "09011223344",
    regular: 5,
    vip: 0,
  },
  {
    id: "TK-006",
    fullName: "Fatima Bello",
    email: "fatima.bello@gmail.com",
    phoneNumber: "08155667788",
    regular: 2,
    vip: 3,
  },
  {
    id: "TK-007",
    fullName: "Samuel Ibrahim",
    email: "samuel.ibrahim@gmail.com",
    phoneNumber: "07044556677",
    regular: 6,
    vip: 1,
  },
  {
    id: "TK-008",
    fullName: "Tolu Akin",
    email: "tolu.akin@yahoo.com",
    phoneNumber: "08199887711",
    regular: 2,
    vip: 2,
  },
  {
    id: "TK-009",
    fullName: "Naana Mensah",
    email: "naana.mensah@hotmail.com",
    phoneNumber: "09022334455",
    regular: 1,
    vip: 5,
  },
  {
    id: "TK-010",
    fullName: "Emeka Okafor",
    email: "emeka.okafor@gmail.com",
    phoneNumber: "08166778899",
    regular: 7,
    vip: 0,
  },
];

export const revenueBreakdown = [
  {
    month: "Jan",
    ticketSold: 30,
    revenue: "50,000",
    percentageTotal: "20%",
  },
  {
    month: "Feb",
    ticketSold: 45,
    revenue: "75,000",
    percentageTotal: "30%",
  },
  {
    month: "Mar",
    ticketSold: 25,
    revenue: "42,500",
    percentageTotal: "17%",
  },
  {
    month: "Apr",
    ticketSold: 38,
    revenue: "63,000",
    percentageTotal: "25%",
  },
  {
    month: "May",
    ticketSold: 52,
    revenue: "90,000",
    percentageTotal: "36%",
  },
  {
    month: "Jun",
    ticketSold: 41,
    revenue: "68,500",
    percentageTotal: "27%",
  },
  {
    month: "Jul",
    ticketSold: 60,
    revenue: "105,000",
    percentageTotal: "42%",
  },
  {
    month: "Aug",
    ticketSold: 48,
    revenue: "82,000",
    percentageTotal: "33%",
  },
  {
    month: "Sep",
    ticketSold: 35,
    revenue: "58,000",
    percentageTotal: "23%",
  },
  {
    month: "Oct",
    ticketSold: 55,
    revenue: "96,000",
    percentageTotal: "38%",
  },
];
